[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GWDA"
authors = [{name = "Yue Zhou, Tianyu Zhao", email = "zzhopezhou@gmail.com"}]
dynamic = ["version", "description"]
